### ISSUE TITLE
Server crashes when blockPlaceEvent is cancelled while placing a Networking Cable

### ISSUE THREAD

**Issue by inklit** [SquidDev-CC/CC-Tweaks#101]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.8.9-1.5.22.6.jar)
  SpongeCoremod (1spongeforge-1.8.9-1890-4.2.0-BETA-1509.jar)
  TweaksLoadingPlugin (CCTweaks-1.8.9-1.0.0.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 7/2/16 1:34 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=modem, clazz=class dan200.computercraft.shared.peripheral.common.BlockCableModemVariant, values=[none, down_off, up_off, north_off, south_off, west_off, east_off, down_on, up_on, north_on, south_on, west_on, east_on, down_off_peripheral, up_off_peripheral, north_off_peripheral, south_off_peripheral, west_off_peripheral, east_off_peripheral, down_on_peripheral, up_on_peripheral, north_on_peripheral, south_on_peripheral, west_on_peripheral, east_on_peripheral]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:67)
    at dan200.computercraft.shared.peripheral.modem.TileCable.getDirection(TileCable.java:267)
    at dan200.computercraft.shared.peripheral.modem.TileCable$1.getDirection(TileCable_Patch.java:51)
    at org.squiddev.cctweaks.core.network.cable.SingleModemCable.canConnectInternally(SingleModemCable.java:14)
    at org.squiddev.cctweaks.core.network.cable.CableWithInternalSidedParts.updateInternalConnectionMap(CableWithInternalSidedParts.java:22)
    at org.squiddev.cctweaks.core.network.cable.CableWithInternalSidedParts.updateConnections(CableWithInternalSidedParts.java:37)
    at org.squiddev.cctweaks.core.network.cable.BasicCable.connect(BasicCable.java:72)
    at org.squiddev.cctweaks.core.network.cable.SingleModemCable.connect(SingleModemCable.java:19)
    at dan200.computercraft.shared.peripheral.modem.TileCable$3.run(TileCable_Patch.java:143)
    at org.squiddev.cctweaks.core.McEvents.onServerTick(McEvents.java:121)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_McEvents_onServerTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:106)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:78)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:594)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Linux (amd64) version 2.6.32-042stab116.1
    Java Version: 1.8.0_45-internal, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 605474688 bytes (577 MB) / 1508372480 bytes (1438 MB) up to 3731947520 bytes (3559 MB)
    JVM Flags: 4 total; -Xmx3584M -Xincgc -XX:ParallelGCThreads=3 -XX:MaxPermSize=128m
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.1890 22 mods loaded, 22 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1890-1.8.9-universal.jar) 
    UCHIJAAAA   Forge{11.15.1.1890} [Minecraft Forge] (forge-1.8.9-11.15.1.1890-1.8.9-universal.jar) 
    UCHIJAAAA   OpenComputers|Core{1.5.22.6} [OpenComputers (Core)] (minecraft.jar) 
    UCHIJAAAA   sponge{1.8.9-1890-4.2.0-BETA-1509} [SpongeForge] (1spongeforge-1.8.9-1890-4.2.0-BETA-1509.jar) 
    UCHIJAAAA   <CCTweaks ASM>{1.0.0} [<CCTweaks ASM>] (minecraft.jar) 
    UCHIJAAAA   io.github.hsyyid.adminshop{1.8.1} [AdminShop] (AdminShop-1.8.9-1.8.1-universal.jar) 
    UCHIJAAAA   ComputerCraft{1.79} [ComputerCraft] (ComputerCraft1.79.jar) 
    UCHIJAAAA   CCTweaks{1.0.0} [CCTweaks] (CCTweaks-1.8.9-1.0.0.jar) 
    UCHIJAAAA   chunkloaderz{1.0.3} [ChunkLoaderZ] (ChunkLoaderZ-1.8.9-1.0.3.jar) 
    UCHIJAAAA   io.github.hsyyid.essentialcmds{@project.informativeVersion@} [EssentialCmds] (EssentialCmds-1.8.9-8.1.11-universal.jar) 
    UCHIJAAAA   griefprevention{1.0} [GriefPrevention] (griefprevention-1.8.9-1.0-12.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   JEI{2.28.9.176} [Just Enough Items] (jei_1.8.9-2.28.9.176.jar) 
    UCHIJAAAA   io.github.hsyyid.kits{1.7.4} [Kits] (Kits-1.7.4.jar) 
    UCHIJAAAA   MoreFurnaces{1.5.1} [More Furnaces] (MoreFurnaces-1.5.1-MC1.8.9.jar) 
    UCHIJAAAA   nuvotifier{2.3.2.2} [NuVotifier] (nuvotifier-universal-2.3.2.2.jar) 
    UCHIJAAAA   OpenComputers{1.5.22.6} [OpenComputers] (OpenComputers-MC1.8.9-1.5.22.6.jar) 
    UCHIJAAAA   ninja.leaping.permissionsex{2.0-SNAPSHOT} [PermissionsEx] (PermissionsEx-Sponge.jar) 
    UCHIJAAAA   com.nguyenquyhy.spongediscord{1.2.0} [Sponge Discord] (Sponge-Discord-1.2.1-all.jar) 
    UCHIJAAAA   totaleconomy{1.4.1} [Total Economy] (TotalEconomy-v1.4.1.jar) 
    UCHIJAAAA   worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1-dist.jar) 
    Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.8.9-1.5.22.6.jar)
  li.cil.oc.common.asm.ClassTransformer
SpongeCoremod (1spongeforge-1.8.9-1890-4.2.0-BETA-1509.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
TweaksLoadingPlugin (CCTweaks-1.8.9-1.0.0.jar)
  org.squiddev.cctweaks.core.asm.ASMTransformer
    Profiler Position: N/A (disabled)
    Player Count: 3 / 50; [EntityPlayerMP['chrapacz2000'/379, l='world', x=5824.05, y=8.00, z=2879.10], EntityPlayerMP['jhagrid7'/453, l='world', x=6451.43, y=77.89, z=2675.36], EntityPlayerMP['BTC'/454, l='world', x=5823.40, y=8.00, z=2879.80]]
    Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
    Type: Dedicated Server (map_server.txt)
```

To reproduce, use GriefPrevention to claim an area, and try placing a networking cable through the claim. Once the block event gets cancelled, the server will crash.

**Comment by SquidDev** [comment]
This should be fixed though I haven't tested with the plugin. I'll try to do that soon and push a build out. Thanks for reporting, sorry about this.

**Comment by SquidDev** [comment]
This should be fixed in 1.0.1. Can you confirm?

**Comment by inklit** [comment]
I will confirm this right now, give me a few minutes to update.

EDIT:
It is fixed.
Thank you.

**Comment by SquidDev** [comment]
Great! Thanks for reporting.
