### ISSUE TITLE
Requires IndustricalCraft 2 (IElectricItem) and thus crashing on refuel. 

### ISSUE THREAD

**Issue by NoLoginFound** [SquidDev-CC/CC-Tweaks#104]
Installing IC2 seems to elimintate the crash. 
Stack trace:

```
java.lang.NoClassDefFoundError: ic2/api/item/IElectricItem
    at org.squiddev.cctweaks.integration.IndustrialCraftIntegration$1.canRefuel(IndustrialCraftIntegration.java:24)
    at org.squiddev.cctweaks.core.turtle.TurtleFuelRegistry.getProvider(TurtleFuelRegistry.java:26)
    at dan200.computercraft.shared.turtle.core.TurtleRefuelCommand.execute(TurtleRefuelCommand_Rewrite.java:31)
    at dan200.computercraft.shared.turtle.core.TurtleBrain.updateCommands(TurtleBrain.java:995)
    at dan200.computercraft.shared.turtle.core.TurtleBrain.update(TurtleBrain.java:183)
    at dan200.computercraft.shared.turtle.blocks.TileTurtle.func_145845_h(TileTurtle.java:278)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: ic2.api.item.IElectricItem
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 13 more
```

**Comment by SquidDev** [comment]
Which version of Minecraft? Can I also have your logs?

**Comment by NoLoginFound** [comment]
1.7.10
crash report:
http://pastebin.com/hPyM7wem
log (not much info in it):
http://pastebin.com/fEzM5aY2

**Comment by NoLoginFound** [comment]
Uninstalled ic2 and tried to reproduce again to get more detailed logs
For a few refuels it was fine, but then finally crashed
Short description of my actions:
Went through the enhanced portal to the mined area where 2 advanced turtles are located. 
Refueled them with block of charcoal and some raw coal, successfully.
Started their mining task (those 2 are equipped with chunkloader from peripherals++)
Killed some zombies and skeletons in the dungeons
Went back through the portal
Put one redstone dust into a simple turtle without any upgrades and commanded it to refuel.
And it crashed as before, complaining that IElectricItem is not found

Here is the detailed log:
[detailed_log.txt](https://github.com/SquidDev-CC/CCTweaks/files/369379/detailed_log.txt)

**Comment by SquidDev** [comment]
Sorry for taking so long to get round to this. There isn't much I can do about this: by the looks of it some mod is packaging the IC2 API but leaving out a load of files. You can try setting `turtle.euRefuelAmount` to `-1` or, if that doesn't work, including the [IC2 API](http://maven.ic2.player.to/net/industrial-craft/industrialcraft-2/2.6.9-ex110/industrialcraft-2-2.6.9-ex110-api.jar) in the mods folder.

**Comment by dirthsj** [comment]
I'd look at MFR, according to your crash report it has loaded it's IC2 integration.
`UCHIJAAAA   MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)`

I would've added AE2, but it claims that IC2 integration is off.
