### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by TheLoneWolfling** [SquidDev-CC/CC-Tweaks#11]
[06/3/2015 13:48:57 PM] Console Cleared
    [06/3/2015 13:49:00 PM] Logging into Minecraft!
    [06/3/2015 13:49:00 PM] Trying to login with access token!
    [06/3/2015 13:49:01 PM] Launching pack Vanilla Minecraft 1.7.10 for Minecraft 1.7.10
    [06/3/2015 13:49:01 PM] Launching Minecraft with the following arguments (user related stuff has been removed): [C:\Program Files\Java\jre7\bin\javaw, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -XX:-OmitStackTraceInFastThrow, -XX:+UseConcMarkSweepGC, -XX:+CMSIncrementalMode, -XX:-UseAdaptiveSizePolicy, -Xms256M, -Xmx4096M, -XX:PermSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=INFO, -Djava.library.path=**USERSDIR**\Instances\Mycraft\bin\natives, -cp, **USERSDIR**\ATLauncher.exe;anything;**USERSDIR**\Instances\Mycraft\jarmods\forge-1.7.10-10.13.2.1236-universal.jar;**USERSDIR**\Instances\Mycraft\bin\launchwrapper-1.11.jar;**USERSDIR**\Instances\Mycraft\bin\asm-all-5.0.3.jar;**USERSDIR**\Instances\Mycraft\bin\akka-actor_2.11-2.3.3.jar;**USERSDIR**\Instances\Mycraft\bin\config-1.2.1.jar;**USERSDIR**\Instances\Mycraft\bin\scala-actors-migration_2.11-1.1.0.jar;**USERSDIR**\Instances\Mycraft\bin\scala-compiler-2.11.1.jar;**USERSDIR**\Instances\Mycraft\bin\scala-continuations-library_2.11-1.0.2.jar;**USERSDIR**\Instances\Mycraft\bin\scala-continuations-plugin_2.11.1-1.0.2.jar;**USERSDIR**\Instances\Mycraft\bin\scala-library-2.11.1.jar;**USERSDIR**\Instances\Mycraft\bin\scala-parser-combinators_2.11-1.0.1.jar;**USERSDIR**\Instances\Mycraft\bin\scala-reflect-2.11.1.jar;**USERSDIR**\Instances\Mycraft\bin\scala-swing_2.11-1.0.1.jar;**USERSDIR**\Instances\Mycraft\bin\scala-xml_2.11-1.0.2.jar;**USERSDIR**\Instances\Mycraft\bin\jopt-simple-4.5.jar;**USERSDIR**\Instances\Mycraft\bin\lzma-0.0.1.jar;**USERSDIR**\Instances\Mycraft\bin\guava-16.0.jar;**USERSDIR**\Instances\Mycraft\bin\commons-lang3-3.2.1.jar;**USERSDIR**\Instances\Mycraft\bin\realms-1.3.5.jar;**USERSDIR**\Instances\Mycraft\bin\commons-compress-1.8.1.jar;**USERSDIR**\Instances\Mycraft\bin\httpclient-4.3.3.jar;**USERSDIR**\Instances\Mycraft\bin\commons-logging-1.1.3.jar;**USERSDIR**\Instances\Mycraft\bin\httpcore-4.3.2.jar;**USERSDIR**\Instances\Mycraft\bin\vecmath-1.3.1.jar;**USERSDIR**\Instances\Mycraft\bin\trove4j-3.0.3.jar;**USERSDIR**\Instances\Mycraft\bin\icu4j-core-mojang-51.2.jar;**USERSDIR**\Instances\Mycraft\bin\codecjorbis-20101023.jar;**USERSDIR**\Instances\Mycraft\bin\codecwav-20101023.jar;**USERSDIR**\Instances\Mycraft\bin\libraryjavasound-20101123.jar;**USERSDIR**\Instances\Mycraft\bin\librarylwjglopenal-20100824.jar;**USERSDIR**\Instances\Mycraft\bin\soundsystem-20120107.jar;**USERSDIR**\Instances\Mycraft\bin\netty-all-4.0.10.Final.jar;**USERSDIR**\Instances\Mycraft\bin\commons-io-2.4.jar;**USERSDIR**\Instances\Mycraft\bin\commons-codec-1.9.jar;**USERSDIR**\Instances\Mycraft\bin\jinput-2.0.5.jar;**USERSDIR**\Instances\Mycraft\bin\jutils-1.0.0.jar;**USERSDIR**\Instances\Mycraft\bin\gson-2.2.4.jar;**USERSDIR**\Instances\Mycraft\bin\authlib-1.5.16.jar;**USERSDIR**\Instances\Mycraft\bin\log4j-api-2.0-beta9.jar;**USERSDIR**\Instances\Mycraft\bin\log4j-core-2.0-beta9.jar;**USERSDIR**\Instances\Mycraft\bin\lwjgl-2.9.1.jar;**USERSDIR**\Instances\Mycraft\bin\lwjgl_util-2.9.1.jar;**USERSDIR**\Instances\Mycraft\bin\twitch-5.16.jar;**USERSDIR**\Instances\Mycraft\bin\minecraft.jar, net.minecraft.launchwrapper.Launch, --username, REDACTED, --version, 1.7.10, --gameDir, **USERSDIR**\Instances\Mycraft, --assetsDir, **USERSDIR**\Configs\Resources, --assetIndex, 1.7.10, --uuid, REDACTED, --accessToken, REDACTED, --userProperties, REDACTED, --userType, mojang, --width=1366, --height=768, --tweakClass=cpw.mods.fml.common.launcher.FMLTweaker]
    [06/3/2015 13:49:02 PM] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
    [06/3/2015 13:49:02 PM] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
    [06/3/2015 13:49:02 PM] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
    [06/3/2015 13:49:02 PM] [main/INFO] [FML]: Forge Mod Loader version 7.10.85.1236 for Minecraft 1.7.10 loading
    [06/3/2015 13:49:02 PM] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_75, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre7
    [06/3/2015 13:49:02 PM] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
    [06/3/2015 13:49:02 PM] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
    [06/3/2015 13:49:02 PM] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
    [06/3/2015 13:49:02 PM] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
    [06/3/2015 13:49:02 PM] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
    [06/3/2015 13:49:04 PM] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
    [06/3/2015 13:49:04 PM] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
    [06/3/2015 13:49:04 PM] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
    [06/3/2015 13:49:04 PM] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
    [06/3/2015 13:49:04 PM] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
    [06/3/2015 13:49:05 PM] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
    [06/3/2015 13:49:05 PM] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
    [06/3/2015 13:49:05 PM] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
    [06/3/2015 13:49:07 PM] [main/INFO]: Setting user: **MINECRAFTUSERNAME**
    [06/3/2015 13:49:08 PM] [Client thread/INFO]: LWJGL Version: 2.9.1
    [06/3/2015 13:49:09 PM] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
    [06/3/2015 13:49:09 PM] [Client thread/INFO] [FML]: MinecraftForge v10.13.2.1236 Initialized
    [06/3/2015 13:49:09 PM] [Client thread/INFO] [FML]: Replaced 182 ore recipies
    [06/3/2015 13:49:09 PM] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
    [06/3/2015 13:49:09 PM] [Client thread/INFO] [FML]: Searching **USERSDIR**\Instances\Mycraft\mods for mods
    [06/3/2015 13:49:12 PM] [Client thread/INFO] [FML]: Forge Mod Loader has identified 6 mods to load
    [06/3/2015 13:49:12 PM] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, <CCTweaks ASM>, CCTweaks, ComputerCraft] at CLIENT
    [06/3/2015 13:49:12 PM] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, <CCTweaks ASM>, CCTweaks, ComputerCraft] at SERVER
    [06/3/2015 13:49:12 PM] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:CCTweaks, FMLFileResourcePack:ComputerCraft
    [06/3/2015 13:49:12 PM] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
    [06/3/2015 13:49:12 PM] // Oh - I know what I did wrong!
    [06/3/2015 13:49:12 PM] 
    [06/3/2015 13:49:12 PM] Time: 3/6/15 1:49 PM
    [06/3/2015 13:49:12 PM] Description: Initializing game
    [06/3/2015 13:49:12 PM] 
    [06/3/2015 13:49:12 PM] java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
    [06/3/2015 13:49:12 PM]     at squiddev.cctweaks.client.ProxyClient.<init>(ProxyClient.java:12)
    [06/3/2015 13:49:12 PM]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    [06/3/2015 13:49:12 PM]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    [06/3/2015 13:49:12 PM]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    [06/3/2015 13:49:12 PM]     at java.lang.reflect.Constructor.newInstance(Unknown Source)
    [06/3/2015 13:49:12 PM]     at java.lang.Class.newInstance(Unknown Source)
    [06/3/2015 13:49:12 PM]     at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
    [06/3/2015 13:49:12 PM]     at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
    [06/3/2015 13:49:12 PM]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [06/3/2015 13:49:12 PM]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at java.lang.reflect.Method.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    [06/3/2015 13:49:12 PM]     at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    [06/3/2015 13:49:12 PM]     at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    [06/3/2015 13:49:12 PM]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [06/3/2015 13:49:12 PM]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at java.lang.reflect.Method.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    [06/3/2015 13:49:12 PM]     at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    [06/3/2015 13:49:12 PM]     at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
    [06/3/2015 13:49:12 PM]     at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
    [06/3/2015 13:49:12 PM]     at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    [06/3/2015 13:49:12 PM]     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    [06/3/2015 13:49:12 PM]     at net.minecraft.client.main.Main.main(SourceFile:148)
    [06/3/2015 13:49:12 PM]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [06/3/2015 13:49:12 PM]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at java.lang.reflect.Method.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    [06/3/2015 13:49:12 PM]     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    [06/3/2015 13:49:12 PM] 
    [06/3/2015 13:49:12 PM] 
    [06/3/2015 13:49:12 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
    [06/3/2015 13:49:12 PM] ---------------------------------------------------------------------------------------
    [06/3/2015 13:49:12 PM] 
    [06/3/2015 13:49:12 PM] -- Head --
    [06/3/2015 13:49:12 PM] Stacktrace:
    [06/3/2015 13:49:12 PM]     at squiddev.cctweaks.client.ProxyClient.<init>(ProxyClient.java:12)
    [06/3/2015 13:49:12 PM]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    [06/3/2015 13:49:12 PM]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    [06/3/2015 13:49:12 PM]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    [06/3/2015 13:49:12 PM]     at java.lang.reflect.Constructor.newInstance(Unknown Source)
    [06/3/2015 13:49:12 PM]     at java.lang.Class.newInstance(Unknown Source)
    [06/3/2015 13:49:12 PM]     at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
    [06/3/2015 13:49:12 PM]     at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
    [06/3/2015 13:49:12 PM]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [06/3/2015 13:49:12 PM]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at java.lang.reflect.Method.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    [06/3/2015 13:49:12 PM]     at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    [06/3/2015 13:49:12 PM]     at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    [06/3/2015 13:49:12 PM]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [06/3/2015 13:49:12 PM]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at java.lang.reflect.Method.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    [06/3/2015 13:49:12 PM]     at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    [06/3/2015 13:49:12 PM]     at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    [06/3/2015 13:49:12 PM]     at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
    [06/3/2015 13:49:12 PM]     at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
    [06/3/2015 13:49:12 PM]     at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    [06/3/2015 13:49:12 PM] 
    [06/3/2015 13:49:12 PM] -- Initialization --
    [06/3/2015 13:49:12 PM] Details:
    [06/3/2015 13:49:12 PM] Stacktrace:
    [06/3/2015 13:49:12 PM]     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    [06/3/2015 13:49:12 PM]     at net.minecraft.client.main.Main.main(SourceFile:148)
    [06/3/2015 13:49:12 PM]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [06/3/2015 13:49:12 PM]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at java.lang.reflect.Method.invoke(Unknown Source)
    [06/3/2015 13:49:12 PM]     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    [06/3/2015 13:49:12 PM]     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    [06/3/2015 13:49:12 PM] 
    [06/3/2015 13:49:12 PM] -- System Details --
    [06/3/2015 13:49:12 PM] Details:
    [06/3/2015 13:49:12 PM]     Minecraft Version: 1.7.10
    [06/3/2015 13:49:12 PM]     Operating System: Windows 8.1 (amd64) version 6.3
    [06/3/2015 13:49:12 PM]     Java Version: 1.7.0_75, Oracle Corporation
    [06/3/2015 13:49:12 PM]     Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    [06/3/2015 13:49:12 PM]     Memory: 114278184 bytes (108 MB) / 259522560 bytes (247 MB) up to 4260102144 bytes (4062 MB)
    [06/3/2015 13:49:12 PM]     JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms256M -Xmx4096M -XX:PermSize=256M
    [06/3/2015 13:49:12 PM]     AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    [06/3/2015 13:49:12 PM]     IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    [06/3/2015 13:49:12 PM]     FML: MCP v9.05 FML v7.10.85.1236 Minecraft Forge 10.13.2.1236 6 mods loaded, 6 mods active
    [06/3/2015 13:49:13 PM]     mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
    [06/3/2015 13:49:13 PM]     FML{7.10.85.1236} [Forge Mod Loader] (forge-1.7.10-10.13.2.1236-universal.jar) Unloaded->Constructed
    [06/3/2015 13:49:13 PM]     Forge{10.13.2.1236} [Minecraft Forge] (forge-1.7.10-10.13.2.1236-universal.jar) Unloaded->Constructed
    [06/3/2015 13:49:13 PM]     <CCTweaks ASM>{0.1.3} [<CCTweaks ASM>] (minecraft.jar) Unloaded->Constructed
    [06/3/2015 13:49:13 PM]     ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) Unloaded->Constructed
    [06/3/2015 13:49:13 PM]     CCTweaks{0.1.3} [CCTweaks] (CCTweaks-1.7.10-0.1.3.jar) Unloaded
    [06/3/2015 13:49:13 PM]     Launched Version: 1.7.10
    [06/3/2015 13:49:13 PM]     LWJGL: 2.9.1
    [06/3/2015 13:49:13 PM]     OpenGL: AMD Radeon HD 7600M Series GL version 4.4.12874 Compatibility Profile Context 14.100.0.0, ATI Technologies Inc.
    [06/3/2015 13:49:13 PM]     GL Caps: Using GL 1.3 multitexturing.
    [06/3/2015 13:49:13 PM] Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
    [06/3/2015 13:49:13 PM] Anisotropic filtering is supported and maximum anisotropy is 16.
    [06/3/2015 13:49:13 PM] Shaders are available because OpenGL 2.1 is supported.
    [06/3/2015 13:49:13 PM] 
    [06/3/2015 13:49:13 PM]     Is Modded: Definitely; Client brand changed to 'fml,forge'
    [06/3/2015 13:49:13 PM]     Type: Client (map_client.txt)
    [06/3/2015 13:49:13 PM]     Resource Packs: []
    [06/3/2015 13:49:13 PM]     Current Language: English (US)
    [06/3/2015 13:49:13 PM]     Profiler Position: N/A (disabled)
    [06/3/2015 13:49:13 PM]     Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    [06/3/2015 13:49:13 PM]     Anisotropic Filtering: Off (1)
    [06/3/2015 13:49:13 PM] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# **USERSDIR**\Instances\Mycraft\crash-reports\crash-2015-03-06_13.49.12-client.txt
    [06/3/2015 13:49:13 PM] process has not exited
    [06/3/2015 13:49:13 PM] java.lang.ProcessImpl.exitValue(Unknown Source)
    [06/3/2015 13:49:13 PM] com.atlauncher.data.Instance$2.run(Instance.java:1150)
    [06/3/2015 13:49:13 PM] Checking for updated files!
    [06/3/2015 13:49:13 PM] No updates found!

My guess is that there's a obfuscation / deobfuscation mismatch somewhere?

**Comment by SquidDev** [comment]
Hmmm, very odd. I'll have a look at that now, thanks!

**Comment by SquidDev** [comment]
I've updated the [0.1.3](https://github.com/SquidDev-CC/CC-Tweaks/releases/tag/v1.7.10-0.1.3) release with a build that should actually work. You were right about the obfuscation issue, looks like I forgot to test in a non-dev environment before release. Thanks!
