### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by JomerDev** [SquidDev-CC/CC-Tweaks#119]
I'm using the latest 1.7.10 version (waiting until 1.10.2 has more updated mods) and it crashes immediately after starting the game. It doesn't event laod anything

Error:
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: org/squiddev/cctweaks/lua/ConfigForgeLoader
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.squiddev.cctweaks.core.Config.init(Config.java:19)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at org.squiddev.cctweaks.core.asm.TweaksLoadingPlugin.<init>(TweaksLoadingPlugin.java:33)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.Class.newInstance(Class.java:438)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: org.squiddev.cctweaks.lua.ConfigForgeLoader
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.security.AccessController.doPrivileged(Native Method)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[14:14:29] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  ... 16 more

**Comment by SquidDev** [comment]
Weird. None of CCTweaks-Lua got packaged with it.

**Comment by JomerDev** [comment]
So should I just add CCTweaks-Lua to it and it should work?

**Comment by SquidDev** [comment]
Yeah, as a temporary fix anyway.

**Comment by JomerDev** [comment]
Nope, that didn't do anything. It still crashes

**Comment by SquidDev** [comment]
It should be fixed now: CCTweaks 1.1.1 should appear on Curse in a few minutes or you can [download it here](https://dl.bintray.com/squiddev/maven/org/squiddev/CCTweaks/1.7.10-1.1.1/CCTweaks-1.7.10-1.1.1.jar).

**Comment by JomerDev** [comment]
Thank you for the fast fix
