### ISSUE TITLE
Still crashing says ComputerCraft isn't installed when it is. 1.11.2

### ISSUE THREAD

**Issue by PartyCrew** [SquidDev-CC/CC-Tweaks#166]
https://gyazo.com/9cbe20419b16cd2b0d8a510a3c4efd7d

Here's the error.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.7.59-ex111.jar)
  MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.109.jar)
  TweaksLoadingPlugin (CCTweaks-1.11.2-1.5.0-pr0.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 6/22/17 12:01 AM
Description: Exception in server tick loop

Missing Mods:
	computercraft : [1.80pr0,)

net.minecraftforge.fml.common.MissingModsException: Mod cctweaks (CCTweaks) requires [computercraft@[1.80pr0,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:271)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:559)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 825291216 bytes (787 MB) / 996671488 bytes (950 MB) up to 996671488 bytes (950 MB)
	JVM Flags: 2 total; -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2315 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge.jar) 
	U	forge{13.20.0.2315} [Minecraft Forge] (forge.jar) 
	U	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	U	<CCTweaks ASM>{1.5.0-pr0} [<CCTweaks ASM>] (minecraft.jar) 
	U	buildcraftfactory{7.99.4} [BC Factory] (buildcraft-7.99.4.jar) 
	U	buildcrafttransport{7.99.4} [BC Transport] (buildcraft-7.99.4.jar) 
	U	buildcraftlib{7.99.4} [BuildCraft Lib] (buildcraft-7.99.4.jar) 
	U	buildcraftbuilders{7.99.4} [BC Builders] (buildcraft-7.99.4.jar) 
	U	buildcraftcore{7.99.4} [BuildCraft] (buildcraft-7.99.4.jar) 
	U	buildcraftenergy{7.99.4} [BC Energy] (buildcraft-7.99.4.jar) 
	U	buildcraftrobotics{7.99.4} [BC Robotics] (buildcraft-7.99.4.jar) 
	U	buildcraftsilicon{7.99.4} [BC Silicon] (buildcraft-7.99.4.jar) 
	U	cctweaks{1.5.0-pr0} [CCTweaks] (CCTweaks-1.11.2-1.5.0-pr0.jar) 
	U	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.4.4.jar) 
	U	fp{25.2.76 pre} [Futurepack] (Futurepack-1.11.2-25.2.76.jar) 
	U	fp.api{1.1.0} [Futurepack API] (Futurepack-1.11.2-25.2.76.jar) 
	U	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.11.2-4.0.0.109.jar) 
	U	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.11.2-4.0.0.109.jar) 
	U	ic2{2.7.59-ex111} [IndustrialCraft 2] (industrialcraft-2-2.7.59-ex111.jar) 
	U	ironchest{1.11.2-7.0.24.809} [Iron Chest] (ironchest-1.11.2-7.0.24.809.jar) 
	U	mekanism{9.3.2} [Mekanism] (Mekanism-1.11.2-9.3.2.309.jar) 
	U	mekanismgenerators{9.3.2} [MekanismGenerators] (MekanismGenerators-1.11.2-9.3.2.309.jar) 
	U	mekanismtools{9.3.2} [MekanismTools] (MekanismTools-1.11.2-9.3.2.309.jar) 
	U	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	U	ropebridge{2.0.5} [Rope Bridge] (ropebridge-1.11.2-2.0.6.jar) 
	U	shipmod{1.0} [The ship mod] (ShipMod-1.1.jar) 
	U	signpost{1.05.5} [Sign Post] (signpost-1.11.2-1.05.5.jar) 
	U	worldedit{6.1.6} [WorldEdit] (worldedit-forge-mc1.11-6.1.6-dist.jar) 
	Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.7.59-ex111.jar)
  
MicdoodlePlugin (MicdoodleCore-1.11.2-4.0.0.109.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
TweaksLoadingPlugin (CCTweaks-1.11.2-1.5.0-pr0.jar)
  org.squiddev.cctweaks.core.asm.ASMTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by SquidDev** [comment]
Can you confirm you downloaded the 1.11.2 version of the mod, rather than the plain old "ComputerCraft" download? If so, can you provide your full logs, as well as a mod list?

Thanks, sorry about this.

**Comment by SquidDev** [comment]
In response to the above, you should probably use [this version of ComputerCraft](http://cc.crzd.me/maven/dan200/computercraft/ComputerCraft-SquidDev-CC-ComputerCraft-feature-minecraft-1.11.2/1.80pr0-build1/ComputerCraft-SquidDev-CC-ComputerCraft-feature-minecraft-1.11.2-1.80pr0-build1.jar) as the later builds have a couple of issues.

**Comment by SquidDev** [comment]
As said before, I'm pretty sure this is a problem with your install. I'm closing this for now but, if you are still encountering problems, do comment - I'm happy to help/reopen this.
