### ISSUE TITLE
Crash when breaking wrapped multipart

### ISSUE THREAD

**Issue by Nathan1852** [SquidDev-CC/CC-Tweaks#46]
I crashed when I connected a Reactor Computer Port from BigReactors to a Networked Modem (the full block) and then broke the Reactor Computer Port

Crashlog:
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at erogenousbeef.bigreactors.common.multiblock.tileentity.TileEntityReactorComputerPort.equals(TileEntityReactorComputerPort.java:372)
	at org.squiddev.cctweaks.blocks.network.TileNetworkedModem.onNeighborChanged(TileNetworkedModem.java:60)
	at org.squiddev.cctweaks.blocks.BlockBase.onNeighborChange(BlockBase.java:78)
	at net.minecraft.world.World.func_147453_f(World.java:3875)
	at net.minecraft.world.World.func_147475_p(World.java:2610)
	at net.minecraft.block.BlockContainer.func_149749_a(SourceFile:21)
	at erogenousbeef.bigreactors.common.multiblock.block.BlockReactorPart.func_149749_a(BlockReactorPart.java:405)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.World.func_147468_f(World.java:573)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1341)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1335)
	at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:247)
	at net.minecraft.server.management.ItemInWorldManager.func_73079_d(ItemInWorldManager.java:240)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:278)
	at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:151)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Nathan1852** [comment]
Is there a new download by any chance?

**Comment by SquidDev** [comment]
Yeah, give me a couple of minutes to push it.

**Comment by SquidDev** [comment]
Right done. [Here](http://maven.bonzodandd.co.uk/org/squiddev/CCTweaks/1.7.10-0.2-pr1/CCTweaks-1.7.10-0.2-pr1.jar) as always.
