### ISSUE TITLE
OpenPeripheral methods not showing

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaks#67]
See http://www.computercraft.info/forums2/index.php?/topic/21987-mc-1710-cc-174-cc-tweaks/page__view__findpost__p__232231

```
Cannot patch openperipheral.interfaces.cc.ModuleComputerCraft, falling back to default
java.lang.IllegalStateException: Cannot find nodes for methods [Method{<clinit>}]
    LDC "computer"
    LDC Ldan200/computercraft/api/peripheral/IComputerAccess;.class
    INVOKEVIRTUAL openperipheral/adapter/composed/MethodSelector.addProvidedEnv (Ljava/lang/String;Ljava/lang/Class;)Lopenperipheral/adapter/composed/MethodSelector;

	at org.squiddev.patcher.visitors.FindingVisitor.visitEnd(FindingVisitor.java:102) ~[CCTweaks-1.7.10-0.2.2.jar:?]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.squiddev.patcher.transformer.TransformationChain.transform(TransformationChain.java:42) ~[CCTweaks-1.7.10-0.2.2.jar:?]
	at org.squiddev.cctweaks.core.asm.ASMTransformer.transform(ASMTransformer.java:121) [CCTweaks-1.7.10-0.2.2.jar:?]
```

[Changed from static constructor to normal constructor](https://github.com/OpenMods/OpenPeripheral/blob/master/src/main/java/openperipheral/interfaces/cc/ModuleComputerCraft.java#L34)

Also, whilst we are doing this I forgot the call to `nodes.accept(mv)`.

**Comment by SquidDev** [comment]
It might be worth re-writing this to remove the need for ASM injection.
The main type we need is the [MethodSelector](https://github.com/OpenMods/OpenPeripheral/blob/master/src/main/java/openperipheral/adapter/composed/MethodSelector.java). This is stored in the [ClassMethodComposer](https://github.com/OpenMods/OpenPeripheral/blob/master/src/main/java/openperipheral/adapter/composed/ClassMethodsComposer.java) class which is stored in the [ComposedMethodFactory](https://github.com/OpenMods/OpenPeripheral/blob/master/src/main/java/openperipheral/adapter/composed/ComposedMethodsFactory.java) class.

So we need to call `PERIPHERAL_METHODS_FACTORY.composer.selector.addProvidedEnv(...)`. However the `composer` and `selector` fields are private.
